services:
  - type: web
    name: verapath
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn --pythonpath leakfix_mvp leakfix_mvp.leakfix.wsgi:application"
    healthCheckPath: "/"
    envVars:
      - key: PYTHONPATH
        value: .
      - key: DATABASE_URL
        value: "REDACTED
      - key: SECRET_KEY
        generateValue: true
      - key: FIELD_ENCRYPTION_KEY
        value: "97q5cO5a-9CrgM75nvoA0y3u8pLiWnCq1vG9v9oP6kQ="
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: DJANGO_SETTINGS_MODULE
        value: leakfix_mvp.leakfix.settings
      - key: PRODUCTION
        value: "True"


