# Generated by Django 5.2.7 on 2025-12-14 20:28

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CPTCodeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordertypeid', models.CharField(help_text='The ID of the referral order type from Athena.', max_length=50, null=True)),
                ('name', models.CharField(help_text='The human-readable name of the referral order type.', max_length=255)),
                ('cpt_code', models.CharField(help_text='The CPT code to use for estimation.', max_length=10)),
                ('work_rvu', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('non_fac_pe_rvu', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('fac_pe_rvu', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('mp_rvu', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100, unique=True)),
                ('last_run_at', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('retained_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-period_start', '-period_end'],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.CharField(max_length=120, unique=True)),
                ('pseudonym', models.CharField(editable=False, max_length=64, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('athena_practice_id', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('work_gpci', models.DecimalField(blank=True, decimal_places=3, default=1.0, max_digits=5, null=True)),
                ('pe_gpci', models.DecimalField(blank=True, decimal_places=3, default=1.0, max_digits=5, null=True)),
                ('mp_gpci', models.DecimalField(blank=True, decimal_places=3, default=1.0, max_digits=5, null=True)),
                ('conversion_factor', models.DecimalField(blank=True, decimal_places=2, default=33.0, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npi', models.CharField(blank=True, max_length=20, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('specialty', models.CharField(blank=True, max_length=120, null=True)),
                ('subspecialty', models.CharField(blank=True, max_length=120, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('accepting_new_patients', models.BooleanField(blank=True, default=True, null=True)),
                ('primary_department', models.CharField(blank=True, max_length=200, null=True)),
                ('is_in_network', models.BooleanField(default=False)),
                ('providerid', models.IntegerField(blank=True, null=True)),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('middleinitial', models.CharField(blank=True, max_length=1, null=True)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('entitytype', models.CharField(blank=True, max_length=50, null=True)),
                ('ansinamecode', models.CharField(blank=True, max_length=255, null=True)),
                ('hideinportal', models.BooleanField(blank=True, default=False, null=True)),
                ('schedulingname', models.CharField(blank=True, max_length=200, null=True)),
                ('billable', models.BooleanField(blank=True, default=False, null=True)),
                ('ansispecialtycode', models.CharField(blank=True, max_length=50, null=True)),
                ('createencounteroncheckin', models.BooleanField(blank=True, default=False, null=True)),
                ('practices', models.ManyToManyField(blank=True, to='analytics.practice')),
            ],
            options={
                'unique_together': {('providerid',)},
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('ack', 'Acknowledged'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled'), ('review', 'Review'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('in_network', models.BooleanField(default=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('documenttypeid', models.CharField(blank=True, max_length=50, null=True)),
                ('rvu_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('referral_date', models.DateField()),
                ('suggested_provider_ids', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ack_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('athena_document_id', models.CharField(blank=True, max_length=50, null=True)),
                ('athena_encounter_id', models.CharField(blank=True, max_length=50, null=True)),
                ('athena_department_id', models.CharField(blank=True, max_length=50, null=True)),
                ('provider_note', models.TextField(blank=True)),
                ('note_to_patient', models.TextField(blank=True)),
                ('visit_summary', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.patient')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.payer')),
                ('practice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.practice')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.provider')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='analytics.referral')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.practice')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
