# Generated by Django 5.2.7 on 2025-12-14 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='practices',
        ),
    ]
