# Generated by Django 5.0.6 on 2025-09-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='suggested_provider_ids',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
