# Generated by Django 5.2.7 on 2025-12-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_remove_provider_practices'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='practices',
            field=models.ManyToManyField(blank=True, to='leakfix_mvp.analytics.practice'),
        ),
    ]
