# Generated by Django 5.0.6 on 2025-09-22 18:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_referral_suggested_provider_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='ack_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReferralHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='analytics.referral')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
    ]
