# Generated by Django 5.0.6 on 2025-09-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_referral_ack_at_referral_cancelled_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('retained_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-period_start', '-period_end'],
            },
        ),
    ]
