# Generated by Django 5.0.6 on 2025-09-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='specialty',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
