# Generated by Django 6.0 on 2025-12-21 19:03

import encrypted_model_fields.fields
from django.db import migrations

def encrypt_existing_data(apps, schema_editor):
    """
    Load every Patient and Referral instance and re-save it to ensure
    the new encrypted fields are written to the database.
    """
    Patient = apps.get_model('analytics', 'Patient')
    Referral = apps.get_model('analytics', 'Referral')
    # Using .iterator() to avoid loading all objects into memory at once
    for patient in Patient.objects.all().iterator():
        patient.save()
    for referral in Referral.objects.all().iterator():
        referral.save() 
def do_nothing(apps, schema_editor):
    """
    This migration is not reversible.
    """
    pass
class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='original_id',
            field=encrypted_model_fields.fields.EncryptedCharField(unique=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='note_to_patient',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='provider_note',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='visit_summary',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.RunPython(encrypt_existing_data, reverse_code=do_nothing),
    ]
