# Generated by Django 6.0 on 2025-12-21 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_alter_patient_first_name_alter_patient_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='is_in_network',
            new_name='is_in_practice_network',
        ),
    ]
