# Generated by Django 5.2.7 on 2025-10-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_referral_specialty'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100, unique=True)),
                ('last_run_at', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
