# Generated by Django 5.2.7 on 2025-10-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_importlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_date',
            field=models.DateField(),
        ),
    ]
