# Generated by Django 5.2.7 on 2025-12-21 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_rename_is_in_network_provider_is_in_practice_network'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='is_in_practice_network',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='in_network',
        ),
        migrations.CreateModel(
            name='ProviderPayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.payer')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.provider')),
            ],
            options={
                'unique_together': {('provider', 'payer')},
            },
        ),
    ]
