# Generated by Django 5.2.7 on 2025-12-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_remove_provider_is_in_practice_network_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='is_in_practice_network',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referral',
            name='is_in_practice_network',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='ProviderPayer',
        ),
    ]
