# Generated by Django 5.2.7 on 2025-10-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_alter_referral_referral_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='is_creation_date_mocked',
            field=models.BooleanField(default=False),
        ),
    ]
