# Generated by Django 5.2.7 on 2025-10-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_referral_is_creation_date_mocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
