# Generated by Django 5.2.7 on 2025-12-21 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_provider_is_in_practice_network_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='provider',
            unique_together=set(),
        ),
    ]
