# Generated by Django 5.2.7 on 2025-10-14 15:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_alter_referral_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
