# Generated by Django 5.2.7 on 2025-10-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_alter_referral_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='subspecialty',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
