# Generated by Django 5.2.7 on 2025-12-24 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
    ]
