# Generated by Django 5.2.7 on 2025-12-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='patient_count',
            field=models.IntegerField(default=0),
        ),
    ]
