# Generated by Django 5.2.7 on 2025-10-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_alter_provider_city_alter_provider_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='provider',
            name='accepting_new_patients',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='average_wait_time',
            field=models.IntegerField(blank=True, help_text='In days', null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='insurances_accepted',
            field=models.ManyToManyField(blank=True, to='analytics.payer'),
        ),
        migrations.AddField(
            model_name='provider',
            name='hospital_affiliations',
            field=models.ManyToManyField(blank=True, to='analytics.hospital'),
        ),
    ]
