# Generated by Django 5.2.7 on 2025-12-24 19:09

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_department_patient_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
