# Generated by Django 5.2.7 on 2025-10-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_hospital_provider_accepting_new_patients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='accepting_new_patients',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
