# Generated by Django 5.2.7 on 2025-12-26 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_patient_first_name_patient_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='ansinamecode',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='ansispecialtycode',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='createencounteroncheckin',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='entitytype',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='hideinportal',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='schedulingname',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='sex',
        ),
    ]
