# Generated by Django 5.2.7 on 2025-12-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0014_remove_provider_ansinamecode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='middleinitial',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
