# Generated by Django 5.2.7 on 2025-10-14 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0014_alter_provider_accepting_new_patients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='is_creation_date_mocked',
        ),
    ]
