# Generated by Django 5.2.7 on 2025-12-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0015_alter_provider_middleinitial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='in_network_payers',
            field=models.ManyToManyField(blank=True, to='analytics.payer'),
        ),
    ]
