# Generated by Django 5.2.7 on 2025-10-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0015_remove_referral_is_creation_date_mocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='specialty',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
