# Generated by Django 5.2.7 on 2025-10-16 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0016_alter_provider_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='primary_department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
