# Generated by Django 5.2.7 on 2025-12-30 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0016_provider_in_network_payers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='in_network_payers',
        ),
    ]
