# Generated by Django 5.2.7 on 2025-10-16 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0017_provider_primary_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='average_wait_time',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='hospital_affiliations',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='insurances_accepted',
        ),
    ]
