# Generated by Django 5.2.7 on 2026-01-03 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0017_remove_provider_in_network_payers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
    ]
