# Generated by Django 5.2.7 on 2025-10-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0018_remove_provider_average_wait_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
    ]
