# Generated by Django 5.2.7 on 2025-10-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0019_referral_is_urgent'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='athena_appointment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
