# Generated by Django 5.2.7 on 2025-10-26 22:55

from django.db import migrations

def create_default_practice(apps, schema_editor):
    Practice = apps.get_model('analytics', 'Practice')
    Practice.objects.create(
        name='VeraPath Practice',
        athena_practice_id='195900'
    )

def delete_default_practice(apps, schema_editor):
    Practice = apps.get_model('analytics', 'Practice')
    Practice.objects.filter(athena_practice_id='195900').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0021_user_profile'),
    ]

    operations = [
        migrations.RunPython(create_default_practice, delete_default_practice),
    ]
