# Generated by Django 5.2.7 on 2025-10-26 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0022_create_default_practice'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.practice'),
        ),
    ]
