# Generated by Django 5.2.7 on 2025-10-26 22:56

from django.db import migrations

def associate_providers(apps, schema_editor):
    Provider = apps.get_model('analytics', 'Provider')
    Practice = apps.get_model('analytics', 'Practice')

    try:
        default_practice = Practice.objects.get(athena_practice_id='195900')
        Provider.objects.all().update(practice=default_practice)
    except Practice.DoesNotExist:
        # If the default practice doesn't exist for some reason, just skip this
        pass

def unassociate_providers(apps, schema_editor):
    # This is not a destructive migration, so we don't need to do anything to reverse it.
    # If we wanted to be thorough, we could set the practice to NULL.
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0023_provider_add_practice'),
    ]

    operations = [
        migrations.RunPython(associate_providers, unassociate_providers),
    ]
