# Generated by Django 5.2.7 on 2025-10-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0024_associate_providers_to_default_practice'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='is_in_network',
            field=models.BooleanField(default=False),
        ),
    ]
