# Generated by Django 5.2.7 on 2025-10-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0025_provider_add_is_in_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
