# Generated by Django 5.2.7 on 2025-10-28 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0026_practice_add_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.provider'),
        ),
    ]
