# Generated by Django 5.2.7 on 2025-10-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0027_referral_provider_on_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='ansinamecode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='ansispecialtycode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='billable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='createencounteroncheckin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='entitytype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='firstname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='hideinportal',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='lastname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='middleinitial',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='providerid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='schedulingname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='sex',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
