# Generated by Django 5.2.7 on 2025-10-29 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0028_provider_add_json_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.practice'),
        ),
    ]
