# Generated by Django 5.2.7 on 2025-10-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0029_userprofile_practice_cascade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='npi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='provider',
            unique_together={('practice', 'providerid')},
        ),
    ]
