# Generated by Django 5.2.7 on 2025-11-13 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0030_provider_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='is_urgent',
        ),
    ]
