# Generated by Django 5.2.7 on 2025-11-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0031_remove_referral_is_urgent'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
    ]
