# Generated by Django 5.2.7 on 2025-11-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0032_referral_is_urgent'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='note_to_patient',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='provider_note',
            field=models.TextField(blank=True),
        ),
    ]
