# Generated by Django 5.2.7 on 2025-11-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0033_referral_note_to_patient_referral_provider_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('ack', 'Acknowledged'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
