# Generated by Django 5.2.7 on 2025-11-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0035_patient_first_name_patient_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='visit_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
