# Generated by Django 5.2.7 on 2025-11-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0036_referral_visit_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='athena_encounter_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
