# Generated by Django 5.2.7 on 2025-11-20 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0037_referral_athena_encounter_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referral',
            old_name='athena_appointment_id',
            new_name='athena_document_id',
        ),
    ]
