# Generated by Django 5.2.7 on 2025-11-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0038_rename_athena_appointment_id_referral_athena_document_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='athena_department_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
