# Generated by Django 5.2.7 on 2025-11-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0039_referral_athena_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('ack', 'Acknowledged'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled'), ('review', 'Review')], default='pending', max_length=20),
        ),
    ]
