# Generated by Django 5.2.7 on 2025-11-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0041_alter_referral_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPTCodeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_order_id', models.CharField(help_text='The ID of the referral order type from Athena.', max_length=50, unique=True)),
                ('referral_order_name', models.CharField(help_text='The human-readable name of the referral order type.', max_length=255)),
                ('cpt_code', models.CharField(help_text='The CPT code to use for estimation.', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this mapping.')),
            ],
        ),
    ]
