# Generated by Django 5.2.7 on 2025-12-06 22:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0042_cptcodemapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cptcodemapping',
            old_name='referral_order_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='cptcodemapping',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='cptcodemapping',
            name='referral_order_id',
        ),
        migrations.AddField(
            model_name='cptcodemapping',
            name='fac_pe_rvu',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='cptcodemapping',
            name='mp_rvu',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='cptcodemapping',
            name='non_fac_pe_rvu',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='cptcodemapping',
            name='ordertypeid',
            field=models.CharField(help_text='The ID of the referral order type from Athena.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cptcodemapping',
            name='work_rvu',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
