# Generated by Django 5.2.7 on 2025-12-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0043_rename_referral_order_name_cptcodemapping_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referral',
            old_name='cost_value',
            new_name='rvu_cost',
        ),
        migrations.AddField(
            model_name='referral',
            name='ordertypeid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
