# Generated by Django 5.2.7 on 2025-12-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0044_rename_cost_value_referral_rvu_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='orderid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
