# Generated by Django 5.2.7 on 2025-12-06 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0045_referral_orderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='ordertypeid',
        ),
    ]
