# Generated by Django 5.2.7 on 2025-12-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0046_remove_referral_ordertypeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='conversion_factor',
            field=models.DecimalField(blank=True, decimal_places=2, default=33.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='practice',
            name='mp_gpci',
            field=models.DecimalField(blank=True, decimal_places=3, default=1.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='practice',
            name='pe_gpci',
            field=models.DecimalField(blank=True, decimal_places=3, default=1.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='practice',
            name='work_gpci',
            field=models.DecimalField(blank=True, decimal_places=3, default=1.0, max_digits=5, null=True),
        ),
    ]
