# Generated by Django 5.2.7 on 2025-12-07 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0047_practice_conversion_factor_practice_mp_gpci_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='orderid',
        ),
    ]
