# Generated by Django 5.2.7 on 2025-12-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0048_remove_referral_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='documenttypeid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
